apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  DB_HOST: app-migration-db.cwr4ikmqyq5m.us-east-1.rds.amazonaws.com
  DB_NAME: gitops_db
  DB_USER: postgres
  DB_PASS: StrongPassword123!
